# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spoko' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spoko
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'


end
